config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    # Lookbook to develop and manage ViewComponents
    mount Lookbook::Engine, at: "/lookbook"

    # Rails Event Store Browser
    mount RailsEventStore::Browser => "/res" if Rails.env.development?
  end

  # Defines the root path route ("/")
  root to: "libraries#index"

  resources :libraries do
    resources :albums, :artists
  end
  resources :folders
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id            :bigint           not null, primary key
#  backdrop_data :jsonb
#  lastfm_url    :string
#  name          :string
#  portrait_data :jsonb
#  slug          :string
#  summary       :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  library_id    :bigint
#  mb_artist_id  :string
#
# Indexes
#
#  index_artists_on_library_id  (library_id)
#  index_artists_on_name        (name) UNIQUE
#  index_artists_on_slug        (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (library_id => libraries.id)
#
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :library, inverse_of: :artists

  has_many :albums, inverse_of: :artist

  validates :name, presence: true,
            uniqueness: { scope: :library_id, message: 'name_not_unique_in_library', case_sensitive: false }
  # validates :mbid, uniqueness: { scope: :library_id, message: "only one unique artist per library" }

  include PortraitUploader::Attachment(:portrait)
  include BackdropUploader::Attachment(:backdrop)

  scope :by_library, ->(library) { where(library: library) }
  scope :by_name, ->(name) { where('name ILIKE ?', "%#{name}%") if name.present? }

  #  before_save do
  #    self.name = self.name.capitalize
  #  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update destroy refresh]

  def index
    @library = Library.includes(:artists).find(params[:library_id])
  end

  def show; end

  private
  def set_artist
    @artist = Artist.friendly.find(params[:id])
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.haml
- content_for(:page_title) do
  = "#{@library.name} - #{t("artist.artists")}"
= turbo_frame_tag "main" do
  .container.mx-auto.p-2
    %h1.font-bold.text-xl= @library.name
    .breadcrumbs
      %ul
        %li= link_to t("library.my_libraries"), libraries_path, data: { turbo_frame: "main" }
        %li= link_to @library.name, library_path(@library), data: { turbo_frame: "main" }
        %li= t("artist.artists")
    .flex.flex-wrap.gap-4
      = render(Artist::CardComponent.with_collection(@library.artists))

app/views/artists/show.html.haml
- content_for(:page_title) do
  = "#{@artist.name} @ #{@artist.library.name}"
= turbo_frame_tag "main" do
  .container.mx-auto.p-2
    %h1.font-bold.text-xl= @artist.library.name
    .breadcrumbs
      %ul
        %li= link_to t("library.my_libraries"), libraries_path
        %li= link_to @artist.library.name, library_path(@artist.library)
        %li= @artist.name
    = render(Artist::HighlightComponent.new(artist: @artist))
    .mt-4.flex.flex-wrap.gap-4
      = render(Album::CardComponent.with_collection(@artist.albums))