config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    # Lookbook to develop and manage ViewComponents
    mount Lookbook::Engine, at: "/lookbook"

    # Rails Event Store Browser
    mount RailsEventStore::Browser => "/res" if Rails.env.development?
  end

  # Defines the root path route ("/")
  root to: "libraries#index"

  resources :libraries do
    resources :albums, :artists
  end
  resources :folders
end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id         :bigint           not null, primary key
#  media_type :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  profile_id :bigint
#
# Indexes
#
#  index_libraries_on_name        (name) UNIQUE
#  index_libraries_on_profile_id  (profile_id)
#
# Foreign Keys
#
#  fk_rails_...  (profile_id => profiles.id)
#
class Library < ApplicationRecord
  belongs_to :profile, inverse_of: :libraries
  
  # generic attributes
  has_many :folders, inverse_of: :library, dependent: :destroy

  # attributes related to Music type libraries
  has_many :albums, inverse_of: :library, dependent: :destroy
  has_many :artists, inverse_of: :library, dependent: :destroy
  
  validates :name, presence: true, uniqueness: { scope: :profile_id, message: 'name_not_unique', case_sensitive: false }

  scope :by_owner, ->(owner) { where(profile: owner) }

  # FeatureEnvy: Library#clean_artists refers to 'artist' more than self (maybe move it to another class?)
  def clean_artists
    artists = Artist.by_library(self)
    artists.each do |artist|
      artist.destroy if artist.albums.empty?
    end
  end

  # FeatureEnvy: Library#clean_albums refers to 'album' more than self (maybe move it to another class?)
  # NilCheck: Library#clean_albums performs a nil-check
  def clean_albums
    albums = Album.by_library(self)
    albums.each do |album|
      album.destroy if album.tracks.empty? || album.artist.nil?
    end
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_library, only: %i[show edit update destroy refresh]

  def index
    if current_user
      @library = Library.includes(:folders).where(profile: current_user.profile)
    end
  end

  def show; end

  def new
    @library = Library.new
  end

  def create
    @library = Library.new(library_params)
    @library.profile = current_user.profile
    
    if @library.save
      respond_to do |format|
        format.html { redirect_to libraries_path, notice: I18n.t('library.creation_success') }
        format.turbo_stream { flash.now[:notice] = I18n.t('library.creation_success') }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_path, notice: I18n.t('library.destruction_success') }
      format.turbo_stream { flash.now[:notice] = I18n.t('library.destruction_success') }
    end
  end

  def update
    @library.folders.each do |folder|
      LibraryIndexationJob.perform_later(folder, current_user)
    end

    respond_to do |format|
      format.html { redirect_to library_path(params[:id]), notice: 'library.refreshing' }
      format.turbo_stream { flash.now[:notice] = I18n.t('library.refreshing') }
    end
  end

  private
  def library_params
    params.require(:library).permit(:name)
  end

  def set_library
    @library = Library.find(params[:id])
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_empty_state.html.haml
.hidden{class: "only:block"}
  .flex.flex-col.items-center.border-8.border-stone-400.border-dashed.p-4
    .font-bold.text-xl.pb-4= t('library.no_library')
    .text-lg.pb-4= t('library.inform')
    .btn.btn-neutral= link_to t('library.new_library'), new_library_path, data: { turbo_frame: dom_id(Library.new) }

app/views/libraries/create.turbo_stream.haml
= turbo_stream.append "libraries" do
  = render(Library::CardComponent.new(library: @library))
= turbo_stream.update Library.new, ""
= render_turbo_stream_flash_messages

app/views/libraries/destroy.turbo_stream.haml
= turbo_stream.remove dom_id(@library)
= render_turbo_stream_flash_messages

app/views/libraries/index.html.haml
- content_for :page_title do
  = "Noizegrid #{t("library.my_libraries")}"
= turbo_frame_tag "main" do
  .container.mx-auto.p-2
    %h1.flex.items-center
      .font-bold.text-xl
        = t("library.my_libraries")
      .btn.btn-circle.btn-ghost
        = link_to new_library_path, data: { turbo_frame: dom_id(Library.new) } do
          = bootstrap_icon "plus-circle", fill: "currentColor", class: "h-6 w-6", title: 'Add a Library', alt: "Add a Library"
    = turbo_frame_tag dom_id(Library.new)
    = turbo_frame_tag "libraries", class: "flex flex-wrap space-x-2 space-y-2" do
      = render "libraries/empty_state"
      = render(Library::CardComponent.with_collection(@library))

app/views/libraries/new.html.haml
= render(Library::FormComponent.new(library: @library, current_user: current_user))

app/views/libraries/show.html.haml
- content_for(:page_title) do
  = @library.name
= turbo_frame_tag "main" do
  .container.mx-auto.p-2
    %h1.font-bold.text-xl= @library.name
    .breadcrumbs
      %ul
        %li= link_to t("library.my_libraries"), libraries_path
        %li= link_to @library.name, library_path(@library)
    %ul.menu.bg-base-300.rounded-box{class: "menu-horizontal"}
      %li=link_to t("artist.artists"), library_artists_path(library_id: @library.id), data: { turbo_frame: "main" }
      %li=link_to t("album.albums"), library_albums_path(library_id: @library.id), data: { turbo_frame: "main" }
    %h2.font-semibold.text-lg= t("library.recently_added")
    %h2.font-semibold.text-lg= t("library.recently_released")
    %h2.font-semibold.text-lg= t("library.recently_updated")

app/views/libraries/update.turbo_stream.haml
= render_turbo_stream_flash_messages
= turbo_stream.update dom_id(@library) do
  = render(Library::CardComponent.new(library: @library))